version: '2'

vars:
  RASPBIAN_SYSROOT: "{{.PWD}}/tmp/rpi-arm"
  RASPBIAN_GCC: "{{.PWD}}/tmp/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc"

tasks:
  # all:
  #   deps: [lint, fmtcheck, vet]

  dslr-amd64:
    desc: build dslr for amd64
    cmds:
    - go build -o bin/gbooth-dslr -v -x -ldflags="-s -w" ./cmd/dslr
    env:
      GOOS: linux
      CGO_ENABLED: 0

  ctl-amd64:
    desc: build ctl for amd64
    cmds:
    - go build -o bin/gbooth-ctl -v -x -ldflags="-s -w" ./cmd/ctl
    env:
      GOOS: linux
      CGO_ENABLED: 0

  core-amd64:
    desc: build core for amd64
    cmds:
    - go build -o bin/gbooth-core -v -x -ldflags="-s -w" ./cmd/core
    env:
      GOOS: linux
      CGO_ENABLED: 1

  ui-amd64:
    desc: build ui for amd64
    cmds:
    - go build -o bin/gbooth-ui -v -x -ldflags="-s -w" ./cmd/ui
    env:
      GOOS: linux
      CGO_ENABLED: 1
      
  buzzer-amd64:
    desc: build buzzer for amd64
    cmds:
    - go build -o bin/gbooth-buzzer -v -x -ldflags="-s -w" ./cmd/buzzer
    env:
      GOOS: linux
      CGO_ENABLED: 0


  dslr-arm:
    desc: build dslr for arm
    cmds:
    - go build -o bin/gbooth-dslr -v -x -ldflags="-s -w" ./cmd/dslr
    deps:
      - dslr-arm-prepare
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      CGO_ENABLED: 0

  ctl-arm:
    desc: build ctl for arm
    cmds:
    - go build -o bin/gbooth-ctl -v -x -ldflags="-s -w" ./cmd/ctl
    deps:
      - dslr-arm-prepare
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      CGO_ENABLED: 0

  core-arm:
    desc: build core for arm
    cmds:
    - go build -o bin/gbooth-core -v -x -ldflags="-s -w" ./cmd/core
    deps:
      - dslr-arm-prepare
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      CGO_ENABLED: 1

      CC: "{{.RASPBIAN_GCC}}"
      CGO_CFLAGS: "--sysroot={{.RASPBIAN_SYSROOT}} -I{{.RASPBIAN_SYSROOT}}/usr/include"
      CGO_LDFLAGS: "--sysroot={{.RASPBIAN_SYSROOT}} -I{{.RASPBIAN_SYSROOT}}/usr/include"
      PKG_CONFIG_DIR: ""
      PKG_CONFIG_PATH: "{{.RASPBIAN_SYSROOT}}/usr/lib/{{.XARCH}}/pkgconfig/"
      PKG_CONFIG_LIBDIR: "{{.RASPBIAN_SYSROOT}}/usr/lib/pkgconfig:{{.RASPBIAN_SYSROOT}}/usr/share/pkgconfig:{{.RASPBIAN_SYSROOT}}/usr/lib/arm-linux-gnueabihf/pkgconfig"
      PKG_CONFIG_SYSROOT_DIR: "{{.RASPBIAN_SYSROOT}}"

  ui-arm:
    desc: build ui for arm
    cmds:
    - go build -o bin/gbooth-ui -v -x -ldflags="-s -w" ./cmd/ui
    deps:
      - dslr-arm-prepare
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      CGO_ENABLED: 1
      
      CC: "{{.RASPBIAN_GCC}}"
      CGO_CFLAGS: "--sysroot={{.RASPBIAN_SYSROOT}} -I{{.RASPBIAN_SYSROOT}}/usr/include"
      CGO_LDFLAGS: "--sysroot={{.RASPBIAN_SYSROOT}} -I{{.RASPBIAN_SYSROOT}}/usr/include"
      PKG_CONFIG_DIR: ""
      PKG_CONFIG_PATH: "{{.RASPBIAN_SYSROOT}}/usr/lib/{{.XARCH}}/pkgconfig/"
      PKG_CONFIG_LIBDIR: "{{.RASPBIAN_SYSROOT}}/usr/lib/pkgconfig:{{.RASPBIAN_SYSROOT}}/usr/share/pkgconfig:{{.RASPBIAN_SYSROOT}}/usr/lib/arm-linux-gnueabihf/pkgconfig"
      PKG_CONFIG_SYSROOT_DIR: "{{.RASPBIAN_SYSROOT}}"
      
  buzzer-arm:
    desc: build buzzer for arm
    cmds:
    - go build -o bin/gbooth-buzzer -v -x -ldflags="-s -w" ./cmd/buzzer
    deps:
      - dslr-arm-prepare
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      CGO_ENABLED: 0

# #  dslr-arm:
# #    desc: build dslr for amd64
# #    deps: 
# #    - dslr-arm-prepare
# #    cmds:
# #    - go build -o bin/gbooth-dslr -v -x -ldflags="-s -w" ./cmd/dslr
# #    env:
#       CC: "{{.RASPBIAN_GCC}}"
#       CGO_CFLAGS: "--sysroot={{.RASPBIAN_SYSROOT}} -I{{.RASPBIAN_SYSROOT}}/usr/include"
#       CGO_LDFLAGS: "--sysroot={{.RASPBIAN_SYSROOT}} -I{{.RASPBIAN_SYSROOT}}/usr/include"
#       # PKG_CONFIG: "{{.RASPBIAN_SYSROOT}}/usr/bin/pkg-config"
#       PKG_CONFIG_DIR: ""
#       PKG_CONFIG_PATH: "{{.RASPBIAN_SYSROOT}}/usr/lib/{{.XARCH}}/pkgconfig/"
#       PKG_CONFIG_LIBDIR: "{{.RASPBIAN_SYSROOT}}/usr/lib/pkgconfig:{{.RASPBIAN_SYSROOT}}/usr/share/pkgconfig:{{.RASPBIAN_SYSROOT}}/usr/lib/arm-linux-gnueabihf/pkgconfig"
#       PKG_CONFIG_SYSROOT_DIR: "{{.RASPBIAN_SYSROOT}}"
# #      GOARCH: arm
# #      GOARM: 7
# #      GOOS: linux
#      CGO_ENABLED: 1

  dslr-arm-prepare:
    desc: prepare environment for arm
    deps: 
    - dslr-arm-image-dev
    - arm-toolchain

  dslr-arm-image-dev:
    desc: build arm image which has all build dependencies for gcc
    cmds:
    - docker build -t dslr:arm-dev -f docker/dslr-arm-dev.Dockerfile docker
    - docker create --name base --entrypoint /bin/sh dslr:arm-dev
    - mkdir -p tmp
    - docker export base > tmp/dslr-arm-dev.tar.gz
    - docker rm base
    - rm -rf tmp/rpi-arm
    - mkdir -p tmp/rpi-arm
    - tar -xf tmp/dslr-arm-dev.tar.gz -C tmp/rpi-arm
    - touch tmp/rpi-arm/updated.info
    generates:
      - "tmp/rpi-arm/updated.info"

  arm-toolchain:
    desc: fetch cross-compiling toolchain
    cmds:
    - mkdir -p tmp/rpi-tools
    - |
      pushd tmp/rpi-tools
      git init
      git remote add origin https://github.com/raspberrypi/tools.git
      git fetch --depth 1 origin master
      git checkout FETCH_HEAD
    - touch tmp/rpi-tools/updated.info
    generates:
      - "tmp/rpi-tools/updated.info"
