# SPDX-License-Identifier: MIT
# Pipeline to run CI

on:
  pull_request:
    branches:
    - master

jobs:
  checks-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: download task
      run: |
        pushd $(mktemp -d)
        wget https://github.com/go-task/task/releases/download/v2.7.0/task_linux_amd64.tar.gz
        tar -xvzf task_linux_amd64.tar.gz
        mv task /opt/
        popd
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gphoto2 libc6 libc6-dev libgphoto2-dev pkg-config libgtk-3-dev
    - name: execute checks
      run: |
        /opt/task checks:all
  
  build-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary: [core, ctl, dslr, ui]
    steps:
    - uses: actions/checkout@v1
    - name: download task
      run: |
        pushd $(mktemp -d)
        wget https://github.com/go-task/task/releases/download/v2.7.0/task_linux_amd64.tar.gz
        tar -xvzf task_linux_amd64.tar.gz
        mv task /opt/
        popd
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gphoto2 libc6 libc6-dev libgphoto2-dev pkg-config libgtk-3-dev
    - name: build
      run: |
        /opt/task build:${{ matrix.binary }}-amd64

    - uses: actions/upload-artifact@master
      with:
        name: "gbooth-${{ matrix.binary }}-amd64"
        path: "bin/gbooth-${{ matrix.binary }}"

  # build-arm:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: download task
  #     run: |
  #       pushd $(mktemp -d)
  #       wget https://github.com/go-task/task/releases/download/v2.7.0/task_linux_amd64.tar.gz
  #       tar -xvzf task_linux_amd64.tar.gz
  #       mv task /opt/
  #       popd
  #   - name: register binfmt multiarch
  #     run: |
  #       docker run --name multiarch --rm --privileged multiarch/qemu-user-static:register
  #   - name: build
  #     run: |
  #       /opt/task build:dslr-arm

  #   - uses: actions/upload-artifact@master
  #     with:
  #       name: gbooth-dslr-arm
  #       path: bin/gbooth-dslr


